spring:
  application:
    name: operador

  datasource:
    url: jdbc:postgresql://localhost:5432/purchases_db
    username: postgres
    password: Mango*0109
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: ms-operador

getBook:
  url: http://buscador/books/%s